# Generated by Django 6.1 on 2026-08-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='pakistan', max_length=100),
            preserve_default=False,
        ),
    ]
